### ISSUE TITLE
support for erlang atom configuration values

### ISSUE THREAD

**Issue by tedgin** [picotrading/ansible-rabbitmq#1]
The `auth_backends` configuration value expects a list of erlang atoms. e.g. `rabbit_auth_backend_internal`, `rabbit_auth_backend_ldap`, etc.  When attempting to use this role to define the `auth_backends` configuration value, it encodes the atoms in the list as strings.

Pretend this is our playbook.

```

---
- hosts: amqp-brokers
  roles:
     - role: jtyr.rabbitmq
       rabbitmq_config:
          - rabbit:
               - auth_backends:
                    - rabbit_auth_backend_internal
```

When run, this generates the following `rabbitmq.config` file.

```
%%
%% This file is managed by Ansible.
%% Do not edit this file manually.
%% Any changes will be automatically reverted.
%%

[
  {rabbit, [
      {auth_backends, [
        "rabbit_auth_backend_internal"
      ]}
  ]}
].
```

The quoted `"rabbit_auth_backend_internal"` names causes authentication to error out.  

Please add support to this role for atom configuration values.

I would be willing to help out with this, if you want. I suspect this will require some of encoding hint being needed in the playbook to tell the encoder that the relevant value is an atom and not a string.
